#!/usr/bin/env python3
import os
import sys
source = os.path.realpath(sys.argv[1])
dest = sys.argv[2]
print(source, dest)
if source[-1] == '/':
    print('Source is a directory, needs to be a file')
    exit()
source, source_file = source.rsplit('/', 1)
source += "/"
if dest[-1] == '/':
    dest_file = source_file
else:
    dest, dest_file = dest.rsplit('/', 1)
    dest += "/"
os.system(f'adb push "{source+source_file}" "{dest+dest_file}"')
os.system(
    f"""adb shell 'am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d "file://{dest+dest_file}"'""")
