#!/usr/bin/env python3
from PIL import Image
from sys import argv
import os
import sys

image = Image.open(argv[1]).convert('RGBA')
color = sorted(image.getcolors(image.width*image.height),key=lambda t: t[0])[-1][1]
size = max(image.width,image.height)
coords = (0,0)
if image.height > image.width:
    coords = (abs(image.height-image.width)//2,0)
else:
    coords = (0,abs(image.height-image.width)//2)

newimage = Image.new('RGBA',(size,size),color)
newimage.paste(image,coords,image)
newimage.save(f"{os.path.splitext(argv[1])[0]}_square.png",compress_level=3)